site_name: TechWiki
site_author: MarkLong
site_description: technology document wiki and blog
site_url: ''
repo_name: sunshine-he/tech-wiki
repo_url: https://github.com/sunshine-he/tech-wiki
copyright: Copyright &copy; 2020-2023 sunshine-he
  

theme: 
  name: 'material'
  custom_dir: overrides
  logo: img/logo.png
  favicon: img/favicon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    annotation: material/arrow-right-circle         
  palette:     
    - media: "(prefers-color-scheme: light)"  
      scheme: default
      primary: teal
      accent: cyan
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode       
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  plugins: 
    - search
    - social
    - tags
    - blog:
        blog_dir: blog
        post_dir: "{blog}/posts"
        blog_toc: false
        post_date_format: full
        post_url_format: "{categories}/{slug}"
        post_url_max_categories: 2
        archive: true
        archive_date_format: yyyy
    - glightbox
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.path
    - navigation.expand
    - navigation.tracking
    - navigation.indexes   
    - toc.follow    
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tooltips
   


extra_css:
  - stylesheets/extra.css
  - stylesheets/typer.css
  - stylesheets/termynal.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/termynal.js
  - javascripts/typer.js  

nav:
  - Home: index.md
  - QuickStart: quick_start.md
  - Development: 
    - Docker: software/docker.md
  - Blog:
    - blog/index.md
    
     
    


# 扩展
markdown_extensions:
  - admonition
  - def_list  
  - md_in_html 
  - pymdownx.superfences        
  - abbr 
  - footnotes  
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true 
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets 
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra:
  generator: false

