site_name: technology document wiki and blog
site_author: MarkLong
site_description: technology document wiki and blog
site_url: ''
repo_name: sunshine-he/tech-wiki
repo_url: https://github.com/sunshine-he/tech-wiki
copyright: Copyright &copy; 2020-2023 sunshine-he
  

theme: 
  name: 'material'
  custom_dir: overrides
  logo: img/logo.png
  favicon: img/favicon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:     
    - media: "(prefers-color-scheme: light)"  
      scheme: default
      primary: blue grey
      accent: cyan
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode       
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  plugins: 
    - search
    - social
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.path
    - navigation.expand
    - navigation.tracking   
    - toc.follow    
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight


extra_css:
  - stylesheets/extra.css
  - stylesheets/typer.css
  - stylesheets/termynal.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/termynal.js
  - javascripts/typer.js  

nav:
  - Home: index.md
  - QuickStart: quick_start.md
  - Development: 
    - actuators: software/pnd_actuator_studio.md
    - python demo: software/python_demo.md



# 扩展
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线


extra:
  generator: false
  # social:
  #   - icon: fontawesome/brands/github-alt
  #     link: https://github.com/tiangolo/typer
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/tiangolo
