name: deploy wiki docs to tencent server

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
permissions:
  contents: write
  pages: write
  id-token: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_actions        
        uses: actions/checkout@v4        
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: setup mkdocs-material
        run: pip install mkdocs-material
      - name: build-docs        
        run: python -m mkdocs build
      - name: Adjust permissions
        run: |
          chmod -c -R +rX site/ | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: site
      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v3
      #   with: 
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
          
         
      
      
          
          
        