name: deploy wiki docs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
permissions:
  contents: write
  pages: write
  id-token: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4        
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: setup mkdocs-material
        run: pip install mkdocs-material
      - run: mkdocs gh-deploy --forece #使用mkdocs的插件发布到github Pages  
      #使用编译生成包再用第三方actions发布github Pages
      # - name: build-docs        
      #   run: python -m mkdocs build
      # - name: Adjust permissions
      #   run: |
      #     chmod -c -R +rX site/ | while read line; do
      #       echo "::warning title=Invalid file permissions automatically fixed::$line"
      #     done
      # - name: Upload to GitHub Pages
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     path: site      
      # - name: Deploy to GitHub pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./site
      #     force_orphan: true
          
         
      
      
          
          
        